version: "2"

services:

# ~ Creates the redis cluster
  redis-cluster-controller-1:
    container_name: dockerland-redis-cluster-controller-1
    image: ${DOCKER_ACCT}/redis-cluster-controller/${TAG}
    build:
      context: .
      dockerfile: .docker/redis-cluster-controller.dockerland.dockerfile
    ports:
      - "6379"
      - "16379"
    working_dir: /redis-3.2.4
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.0.3

# ~ Redis Master Nodes ~ #
  redis-m1:
    container_name: dockerland-redis-m1
    image: ${DOCKER_ACCT}/redis/${TAG}
    build: 
      context: .
      dockerfile: .docker/redis.dockerland.dockerfile
    ports:
      - "6381:6379"
      - "16381:16379"
    working_dir: /
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.1.1

  redis-m2:
    container_name: dockerland-redis-m2
    image: ${DOCKER_ACCT}/redis/${TAG}
    build: 
      context: .
      dockerfile: .docker/redis.dockerland.dockerfile
    ports:
      - "6382:6379"
      - "16382:16379"
    working_dir: /
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.1.2

  redis-m3:
    container_name: dockerland-redis-m3
    image: ${DOCKER_ACCT}/redis/${TAG}
    build: 
      context: .
      dockerfile: .docker/redis.dockerland.dockerfile
    ports:
      - "6383:6379"
      - "16383:16379"
    working_dir: /
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.1.3

# ~ Redis Slave Nodes ~ #
  redis-s1:
    container_name: dockerland-redis-s1
    image: ${DOCKER_ACCT}/redis/${TAG}
    build: 
      context: .
      dockerfile: .docker/redis.dockerland.dockerfile
    ports:
      - "6384:6379"
      - "16384:16379"
    working_dir: /
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.2.1

  redis-s2:
    container_name: dockerland-redis-s2
    image: ${DOCKER_ACCT}/redis/${TAG}
    build: 
      context: .
      dockerfile: .docker/redis.dockerland.dockerfile
    ports:
      - "6385:6379"
      - "16385:16379"
    working_dir: /
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.2.2

  redis-s3:
    container_name: dockerland-redis-s3
    image: ${DOCKER_ACCT}/redis/${TAG}
    build: 
      context: .
      dockerfile: .docker/redis.dockerland.dockerfile
    ports:
      - "6386:6379"
      - "16386:16379"
    working_dir: /
    networks:
      dockerland-network-redis-cluster:
        ipv4_address: 172.24.2.3

networks:

  dockerland-network-redis-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.24.0.0/16
        gateway: 172.24.0.1